import type { Config } from 'tailwindcss';

const config: Config = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "dark/text/secondary": "#949fa8",
        "systematic/blue/border": "#78d3f840",
        "systematic/yellow/system": "#fbe5a2",
        "systematic/orange/border": "#faad1540",
        "systematic/blue/background": "#78d3f8",
        "systematic/green/positive": "#34cf82",
        "chart/gray-transparent": "#99add11a",
        "chart/yellow-light": "#fbe5a2",
        "systematic/green/background": "#34cf822e",
        "chart/orange-light": "#ffd8b8",
        "dark/text/disabled": "#949fa8b2",
        "dark/text/primary": "#f2f4f5",
        "chart/greek": "#6176ff",
        "systematic/red/negative": "#ff7f7b",
        "systematic/blue/info": "#78d3f8",
        "chart/green-light": "#aad8d8",
        "chart/purple-light": "#dbd7fd",
        "chart/gray-light": "#b4c8ed",
        "chart/purple": "#9a8fff",
        "systematic/green/accent": "#34cf824d",
        "systematic/orange/warning": "#faad15",
        "chart/blue": "#00a5ff",
        "chart/greek-light": "#bdd2fd",
        "chart/cyan-light": "#bdefdb",
        "chart/goldenpurple": "#9661bc",
        "chart/goldenpurple-light": "#d3c6ea",
        "chart/green": "#008a89",
        "chart/blue-light": "#b2e4ff",
        "systematic/red/accent": "#ff7f7b4d",
        "chart/magenta-light": "#ffd6e7",
        "chart/greek-transparent": "#6176ff1a",
        "chart/magenta": "#f08bb4",
        "chart/cyan": "#58d1c9",
        "systematic/blue/tag": "#263ea0",
        "chart/yellow": "#f6bd16",
        "chart/orange": "#f6903d",
        "systematic/orange/background": "#faad152e",
        "chart/gray": "#99add1",
        "systematic/red/background": "#ff7f7b2e",
        "systematic/red/notification": "#ff4242",
        "ref/neutral/gray500": "#273545",
        "ref/neutral/gray200": "#6c7c89",
        "ref/neutral/gray50": "#f2f4f5",
        "white": "#ffffff",
        "ref/neutral/gray300": "#5e6f7d",
        "ref/neutral/gray100": "#949fa8",
        "black": "#000000",
        "dark/chip/customlabel": "#1e2b38",
        "dark/chip/filter": "#303e4f",
        "dark/chip/label": "#253446",
        "dark/primary/main": "#00ffa7",
        "ref/neutral/gray400": "#3e5160",
        "dark/other/dialog": "#16222d",
        "ref/neutral/gray800": "#121c26",
        "dark/background/paper/elevation1": "#121c26",
        "dark/background/paper/elevation2": "#16222d",
        "dark/primary/pressed": "#09c385",
        "dark/other/outline": "#2b3540",
        "ref/primary/teal500": "#00ffa7",
        "ref/primary/teal900": "#122927",
        "dark/primary/disabled": "#00ffa859",
        "ref/neutral/gray700": "#16222d",
        "dark/background/paper/elevation3": "#1f2833",
        "dark/action/elevated-hover": "#2b3540",
        "ref/primary/teal400": "#3cf6b8",
        "ref/neutral/gray900": "#061019",
        "dark/primary/selected-background": "#122927",
        "dark/action/default-hover": "#16222d",
        "dark/primary/hovered": "#3cf6b8",
        "dark/action/focused": "#0f1a24",
        "dark/background/default": "#061019",
        "ref/primary/teal600": "#09c385",
        "dark/other/divider": "#2b3540",
        "ref/neutral/gray600": "#1f2833"
      },
      "typography": {}
    }
  },
  "plugins": []
};

export default config;